### ISSUE TITLE
Unable to create a project

### ISSUE THREAD

**Issue by UMjp** [umsi/query_improver#1]
I can't create a project, which is the main interface for project management, in this repo. It seems that I don't have permission to create a project in a repo owned by UMSI (I am able to do this in my forked version).

**Comment by UMjp** [comment]
That said, if we can't create a project in this repo, we could still use this Issue tracker for project management, which you had mentioned on Monday. It won't have all the capabilities that a project does, but it might still be enough.

**Comment by presnick** [comment]
I created a project and linked it to the repository, and also gave you full
admin rights to the repository.

Did you find something from the documentation about a good configuration
for us?
